<?php
/**
 * Application Configuration
 */

// Application settings
define('APP_NAME', 'School Management System');
define('APP_VERSION', '1.0.0');
define('APP_URL', 'http://localhost');
define('APP_DEBUG', true);

// Session settings
define('SESSION_LIFETIME', 3600); // 1 hour
define('SESSION_COOKIE_LIFETIME', 86400); // 24 hours
define('SESSION_NAME', 'SMS_SESSION');

// Security settings
define('CSRF_PROTECTION', true);
define('PASSWORD_MIN_LENGTH', 8);
define('LOGIN_ATTEMPTS', 5);
define('LOCKOUT_TIME', 900); // 15 minutes

// File upload settings
define('UPLOAD_MAX_SIZE', 5 * 1024 * 1024); // 5MB
define('UPLOAD_ALLOWED_TYPES', [
    'image/jpeg',
    'image/png',
    'image/gif',
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
]);
define('UPLOAD_PATH', BASE_PATH . '/backend/public/uploads/');

// Pagination settings
define('PER_PAGE', 20);
define('PER_PAGE_OPTIONS', [10, 20, 50, 100]);

// Email settings
define('MAIL_MAILER', 'smtp');
define('MAIL_HOST', 'smtp.gmail.com');
define('MAIL_PORT', 587);
define('MAIL_USERNAME', '');
define('MAIL_PASSWORD', '');
define('MAIL_ENCRYPTION', 'tls');
define('MAIL_FROM_ADDRESS', 'noreply@school.com');
define('MAIL_FROM_NAME', APP_NAME);

// Cache settings
define('CACHE_DRIVER', 'file');
define('CACHE_PATH', BASE_PATH . '/backend/storage/cache');
define('CACHE_TTL', 3600); // 1 hour

// Logging settings
define('LOG_CHANNEL', 'stack');
define('LOG_LEVEL', 'debug');
define('LOG_PATH', BASE_PATH . '/backend/logs');

// Backup settings
define('BACKUP_PATH', BASE_PATH . '/backend/storage/backups');
define('BACKUP_RETENTION_DAYS', 30);

// API settings
define('API_VERSION', 'v1');
define('API_RATE_LIMIT', 1000); // requests per hour
define('API_KEY_HEADER', 'X-API-Key');

// Timezone
define('APP_TIMEZONE', 'Asia/Kolkata');

// Date format
define('DATE_FORMAT', 'Y-m-d');
define('DATETIME_FORMAT', 'Y-m-d H:i:s');
define('DISPLAY_DATE_FORMAT', 'd/m/Y');
define('DISPLAY_DATETIME_FORMAT', 'd/m/Y H:i');

// Currency settings
define('CURRENCY_SYMBOL', '₹');
define('CURRENCY_CODE', 'INR');

// School information (to be updated via admin panel)
define('SCHOOL_NAME', 'Springfield International School');
define('SCHOOL_ADDRESS', '123 Education Street, Knowledge City');
define('SCHOOL_PHONE', '+91-1234567890');
define('SCHOOL_EMAIL', 'info@springfield.edu');
define('SCHOOL_WEBSITE', 'https://springfield.edu');

// Academic year settings
define('CURRENT_ACADEMIC_YEAR', '2024-2025');
define('ACADEMIC_YEAR_START', '04-01');
define('ACADEMIC_YEAR_END', '03-31');

// Report settings
define('REPORT_LOGO', UPLOAD_PATH . 'school_logo.png');
define('REPORT_HEADER', SCHOOL_NAME);
define('REPORT_FOOTER', 'Generated by ' . APP_NAME . ' v' . APP_VERSION);

// SMS settings (for notifications)
define('SMS_API_KEY', '');
define('SMS_API_SECRET', '');
define('SMS_SENDER_ID', 'SCHOOL');

// Payment gateway settings
define('RAZORPAY_KEY', '');
define('RAZORPAY_SECRET', '');
define('PAYPAL_CLIENT_ID', '');
define('PAYPAL_CLIENT_SECRET', '');

// Social login settings
define('GOOGLE_CLIENT_ID', '');
define('GOOGLE_CLIENT_SECRET', '');
define('FACEBOOK_APP_ID', '');
define('FACEBOOK_APP_SECRET', '');

// Maintenance mode
define('MAINTENANCE_MODE', false);
define('MAINTENANCE_MESSAGE', 'System is under maintenance. Please try again later.');

// Feature flags
define('ENABLE_NOTIFICATIONS', true);
define('ENABLE_SMS', false);
define('ENABLE_EMAIL', true);
define('ENABLE_BACKUP', true);
define('ENABLE_AUDIT_LOG', true);
define('ENABLE_TWO_FACTOR', false);

// Third-party integrations
define('ZOOM_API_KEY', '');
define('ZOOM_API_SECRET', '');
define('GOOGLE_CLASSROOM_CLIENT_ID', '');
define('GOOGLE_CLASSROOM_CLIENT_SECRET', '');